# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc 'Builds project and executes unit tests'
    lane :unit_test do |options|
      scan(
        clean: options[:clean] || false,
        skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution] || false
      )
    end

    desc 'Run only LoginView tests'
    lane :test_login do
      scan(
        only_testing: ["FoodOnlineOrderDeliveryTests/LoginViewTests"]
      )
    end

    desc 'Run tests with full output'
    lane :test_verbose do
      scan(
        output_types: "html,junit",
        open_report: true
      )
    end
end
